// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YaVAIhYGBspbu3z4oImTXgnHDUH06cQ',
    appId: '1:103944605129:web:595e35e747c604654f2c18',
    messagingSenderId: '103944605129',
    projectId: 'chat-notify-system',
    authDomain: 'chat-notify-system.firebaseapp.com',
    storageBucket: 'chat-notify-system.firebasestorage.app',
    measurementId: 'G-56BX5F52MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9T7nY-7q2D4i9j7sEUAiQ6LZppgmv464',
    appId: '1:103944605129:android:04cd031d4253b67b4f2c18',
    messagingSenderId: '103944605129',
    projectId: 'chat-notify-system',
    storageBucket: 'chat-notify-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNCX2qSoDbybNcXDMzSDrgqFAS7mt5Gp4',
    appId: '1:103944605129:ios:70f9db6ce11d2def4f2c18',
    messagingSenderId: '103944605129',
    projectId: 'chat-notify-system',
    storageBucket: 'chat-notify-system.firebasestorage.app',
    iosBundleId: 'com.example.chatNotifySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNCX2qSoDbybNcXDMzSDrgqFAS7mt5Gp4',
    appId: '1:103944605129:ios:70f9db6ce11d2def4f2c18',
    messagingSenderId: '103944605129',
    projectId: 'chat-notify-system',
    storageBucket: 'chat-notify-system.firebasestorage.app',
    iosBundleId: 'com.example.chatNotifySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5YaVAIhYGBspbu3z4oImTXgnHDUH06cQ',
    appId: '1:103944605129:web:f5b935d2010298f74f2c18',
    messagingSenderId: '103944605129',
    projectId: 'chat-notify-system',
    authDomain: 'chat-notify-system.firebaseapp.com',
    storageBucket: 'chat-notify-system.firebasestorage.app',
    measurementId: 'G-0NB3T37T8L',
  );
}
